version: '2'
services:
  locust-master:
    image: locust_distribute
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    environment:
      SCENARIO_FILE: /home/locust/locustfile.py
      LOCUST_MODE: master
      TARGET_URL: http://112.74.93.133:3001
    volumes:
      - ./:/home/locust/
  locust-slave:
    image: locust_distribute
    links:
      - locust-master
    volumes:
      - ./:/home/locust/
    environment:
      SCENARIO_FILE: /home/locust/locustfile.py
      LOCUST_MODE: slave
      TARGET_URL: http://112.74.93.133:3001
      MASTER_HOST: 112.74.114.59
    
      
